version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 20
    rebase-strategy: "disabled"
    assignees:
      - jsnel
      - s-weigand
    groups:
      Python:
        update-types:
          - minor
          - patch
      Python-CVE:
        update-types:
          - minor
          - patch
        applies-to: security-updates
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday
      time: "18:00"
      timezone: Europe/Amsterdam
    assignees:
      - s-weigand
    groups:
      GH-Actions:
        update-types:
          - minor
          - patch
    rebase-strategy: "disabled"
