#:schema https://json.schemastore.org/ruff.json
extend = ".ruff.toml"

extend-exclude = [
  "docs/conf.py",
]

[lint]
extend-ignore = [
  "D",
  "E402",
  "F404",
  "I002", # from __future__ import annotations
]

[lint.isort]
required-imports = []
force-single-line = false
