#:schema https://json.schemastore.org/ruff.json
extend = ".ruff.toml"

[lint]
extend-ignore = [
  "D",
  "E402",
  "F404",
  "I002", # from __future__ import annotations
]

[isort]
required-imports = []
force-single-line = false
