
select = [
  "E", # pycodestyle
  "W", # pycodestyle
  "C", # mccabe
  "F", # pyflakes
  "UP", # pyupgrade
  "D", # pydocstyle
  "N", # pep8-naming
  "YTT", # flake8-2020
  "BLE", # flake8-blind-except
  # "FBT", # flake8-boolean-trap
  "B", # flake8-bugbear
  "C4", # flake8-comprehensions
  "T10", # flake8-debugger
  "FA", # flake8-future-annotations
  "EM", # flake8-errmsg
  "I", # isort (activates import sorting for formatter)
  "ISC", # flake8-implicit-str-concat
  "INP", # flake8-no-pep420
  "PIE", # flake8-pie
  "T20", # flake8-print
  "PT", # flake8-pytest-style
  "RSE", # flake8-raise
  "RET", # flake8-return
  "SIM", # flake8-simplify
  "TCH", # flake8-type-checking
  "ARG", # flake8-unused-arguments
  "PTH", # flake8-use-pathlib
  "ERA", # eradicate
  "PD", # pandas-vet
  "PGH", # pygrep-hooks
  "NPY", # NumPy-specific
  "RUF", # Ruff-specific
]

ignore = [
  "D202",
  "D213",
  "D203",
  "ISC002",
  "RUF001",
  "RUF002",
  "RUF003",
  "B008",
  # Covered by formatter
  "ISC001",
]

# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
  "docs/conf.py",
]
# Same as Black.
line-length = 99

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"

# Enable using ruff with notebooks
extend-include = ["*.ipynb"]

[per-file-ignores]
"tests/*" = ["ARG001"]

[isort]
required-imports = ["from __future__ import annotations"]
known-first-party = ["pyglotaran_extras"]
force-single-line = true
